Vagrant.configure("2") do |config|
    
    # nextjs web/api server 
    config.vm.define "web" do |web|
      web.vm.box = "ubuntu/bionic64"
      web.vm.provider "virtualbox" do |vb|
        vb.name = "dseng-web"
      end
      web.vm.synced_folder "./app", "/home/vagrant/app"
      web.vm.network "private_network", ip: "192.168.11.111"
      web.vm.provision "shell", path: "./next.sh"
    end
    
    # db server
    config.vm.define "db" do |db|
      db.vm.box = "ubuntu/bionic64"
      db.vm.provider "virtualbox" do |vb|
        vb.name = "dseng-db"
      end
      db.vm.network "private_network", ip: "192.168.11.110"
      db.vm.provision "shell", path: "./mysql.sh"
    end
    
  end
  
  